### PR TITLE
Stop invoking setup.py directly

### PR DESCRIPTION
**Pull request by anderslindho**
I saw that this project made use of `setup.py` as well as a number of `requirements.txt` files for setting up environments. The general recommendation is to no longer invoke `setup.py` directly (find a good recap [here](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)), so I've made some changes to the build configuration in case you're interested.

I have updated the instructions in the README but have not modified the CHANGELOG.

I also noted some more things as I was doing this:
- You make use of flake8 for some linting and checking on formatting. I don't know if you have opinions, but I would recommend using `black` for formatting, and `pre-commit` for automatic formatting (and linting), and to integrate `pre-commit` with the CI/CD. I could set this up for you if you'd like.
- The tests appear to have been deactivated because some of them require direct access to IO not existing on headless systems (like the CI/CD runners). I did some brief attempts to try and exclude certain tests (in order to reactivate `tox` in GH actions) but unsuccessfully so; if this would be of interest, however, I could try a bit further.
- The badge for the documentation says that the docs are failing, both after and before my MR. Would you like me to look into this?

### CODE REVIEW

**Comment by einarf** [comment]
Thanks. The reason I've been delaying this change is a github bug that causes the repo to no longer be recognized as a python package losing all links to dependencies and projects depending on moderngl-window. If this is still an issue we still need a setup.py in the repo at the very least. I could try to merge this and see what happens,

**Comment by anderslindho** [comment]
> Thanks. The reason I've been delaying this change is a github bug that causes the repo to no longer be recognized as a python package losing all links to dependencies and projects depending on moderngl-window. If this is still an issue we still need a setup.py in the repo at the very least. I could try to merge this and see what happens,

That's curious. Do you want me to add back a minimal `setup.py` for compatability or leave it be?

**Comment by einarf** [comment]
Nah. Let's just see what happens. Should be easy to add a skeleton setup.py if needed 😄 

Just need to find a good time. Very soon.

**Comment by einarf** [comment]
Note to self: Also check docs

**Comment by einarf** [comment]
Kind of forgot about this. Will merge it in next next release. I'll fix the conflcs, so just let this one linger.

**Comment by einarf** [comment]
I'll try to slavage this PR to respect the time you spent on this. Seems the simplest way it to merge in master, tweak a bit and squash it.

**Comment by einarf** [comment]
Merged two years later. Better now than never 😆

**Pull request merged**
