### PR TITLE
Key handling

### PR DESCRIPTION
**Pull request by OKaluza**
- Added support for ALT key in modifier flags
- Fixed qt modifier flags, required casting to bool to match other windows
- Fixed qt mapping of keys.ENTER to the numpad key only, swapped for the main keyboard key
- Update modifier keys for use in mouse events

### CODE REVIEW

**Comment by einarf** [comment]
Thanks a lot for this. I'll have a look very soon. I'm positively suprised someone even bothered to this in all window backends 😄 (More like shocked)

**Comment by OKaluza** [comment]
No worries, thanks for your work! I know the pain of trying to get consistent mouse/key handling behaviour on multiple platforms/libraries, having dealt with it on the C++ side. If I can use moderngl_window and move it to the python side it will make my life easier.

**Comment by einarf** [comment]
Looks good!

I have similar reasons for creating this project. Not getting stuck on a window library is also good. I had a huge C++ application (opengl) I just could not maintain easily. Changed to python/moderngl with C extensions for doing the heavly lifting like creating building vertex data. Dumping that data into buffers on the python side i moderngl.

If you have any ideas for improvements don't hesitate to make an issue or pr.

**Comment by einarf** [comment]
New version released: https://pypi.org/project/moderngl-window/2.1.1/

**Comment by OKaluza** [comment]
Thanks for this! Using the new pypi version and all working great.

**Pull request merged**
